#==========================================
# @ConfigName        havingautism自用Clash配置文件Lite版
# @Author            @havingautism
# @UpdateTime        2025/04/01 
# @ClashVerge        https://github.com/clash-verge-rev/clash-verge-rev/releases
# @Thanks            @blackmatrix7
#==========================================
mixed-port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: :9090
proxy-providers:
  Airport01:
    type: http
    url: http://example.com
    #更改为自己订阅机场的地址
    interval: 86400
    path: ./Airport01.yaml
    health-check:
      enable: true
      interval: 600
      url: http://cp.cloudflare.com/generate_204

dns:
  enable: true
  prefer-h3: true
  listen: 127.0.0.1:53
  ipv6: false
  nameserver-policy:
    'linux.do': 'udp://223.6.6.6:53'
    "geosite: cn,private,Apple":
      - https://223.5.5.5/dns-query#h3=true
      - https://223.6.6.6/dns-query#h3=true
      - udp://223.6.6.6:53
    "rule-set:applications,SteamCN,GameDownloadCN,Epic,Speedtest":
      - https://223.5.5.5/dns-query#h3=true
      - https://223.6.6.6/dns-query#h3=true
      - udp://223.6.6.6:53
  nameserver:
    - udp://1.0.0.1:53
    - udp://8.8.4.4:53
    - https://1.0.0.1/dns-query
    - tls://one.one.one.one:853
    - tls://8.8.4.4:853
    - https://8.8.4.4/dns-query
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query#h3=true
    - https://223.6.6.6/dns-query#h3=true
    - udp://223.6.6.6:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"     


# proxies: []
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 流媒体节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 英国节点
      - 韩国节点
      - 手动切换
      - DIRECT
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Available.png

  - name: 手动切换
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Server.png
    use: [Airport01]

  - name: 流媒体节点选择
    type: select
    proxies:
      - 流媒体节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 英国节点
      - 韩国节点
      - 手动切换
      - DIRECT
    # icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Auto.png
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Available_1.png

  - name: 流媒体节点
    type: select
    use: [Airport01]
    filter: 0.2|0.3|实验性
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ForeignMedia.png

  - name: 香港节点
    type: select
    use: [Airport01]
    filter: 港|🇭🇰|香港|HK|Hong
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png

  - name: 美国节点
    type: select
    filter: 美|🇺🇸|美国|US|States|American
    use: [Airport01]
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png
  
  # - name: 自动选择
  #   type: url-test
  #   url: http://www.gstatic.com/generate_204
  #   interval: 300
  #   tolerance: 50
  #   use: [Airport01]
  #   icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Available_1.png

  - name: 国外视频
    type: select
    proxies:
      - 节点选择
      - 流媒体节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 手动切换
      - DIRECT
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Netflix.png
    
  - name: Google
    type: select
    proxies:
      - DIRECT
      - 节点选择
      - 美国节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 手动切换
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Google_Search.png
  
  - name: Spotify
    type: select
    proxies:
      - 节点选择
      - 流媒体节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Spotify.png

  - name: Github
    type: select
    proxies:
      - DIRECT
      - 节点选择
      - 美国节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 手动切换
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/GitHub.png

  - name: Telegram
    type: select
    proxies:
      - 节点选择
      - 流媒体节点选择
      - 狮城节点
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - DIRECT
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Telegram.png

  - name: AI
    type: select
    proxies:
      - 节点选择
      - 狮城节点
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - DIRECT
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Copilot.png

  - name: Steam
    type: select
    proxies:
      - 节点选择
      - 流媒体节点选择
      - 狮城节点
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - DIRECT
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Steam.png
  
  - name: Instagram
    type: select
    proxies:
      - 节点选择
      - 流媒体节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Instagram.png
  
  - name: Twitter
    type: select
    proxies:
      - 节点选择
      - 流媒体节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 手动切换
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Twitter.png


  - name: Microsoft
    type: select
    proxies:
      - DIRECT
      - 节点选择
      - 美国节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 手动切换
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Microsoft.png

  - name: Apple
    type: select
    proxies:
      - DIRECT
      - 节点选择
      - 美国节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 手动切换
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Apple.png

  - name: 漏网之鱼
    type: select
    proxies:
      - 节点选择
      - DIRECT
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 英国节点
      - 手动切换
    icon: https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Final.png

  - name: 日本节点
    type: select
    filter: 日|🇯🇵|日本|JP|Japan
    use: [Airport01]
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png


  - name: 台湾节点
    type: select
    filter: 台|🇨🇳|台湾|TW|Tai
    use: [Airport01]
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Taiwan.png

  - name: 狮城节点
    type: select
    filter: 坡|🇸🇬|新加坡|狮城|SG|Singapore
    use: [Airport01]
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Singapore.png

  - name: 英国节点
    type: select
    filter: 🇬🇧|英国|英|英格兰|UK|United Kingdom
    use: [Airport01]
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_Kingdom.png

  - name: 韩国节点
    type: select
    filter: 🇰🇷|韩|KR|KOR|Korea
    use: [Airport01]
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Korea.png


rule-providers:
  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    path: ./ruleset/Spotify.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Spotify/Spotify.yaml
    interval: 86400
  Github:
    type: http
    behavior: classical
    path: ./ruleset/Github.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.yaml
    interval: 86400
  Apple:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Apple.yaml
    path: ./ruleset/Apple.yaml
    interval: 86400
  ChinaIP:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/soffchen/GeoIP2-CN@release/clash-rule-provider.yml
    path: ./ruleset/ChinaIP.yaml
    interval: 86400
  Google:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml
    path: ./ruleset/GoogleFCM.yaml
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix_Classical.yaml
    path: ./ruleset/Netflix.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./ruleset/Microsoft.yaml
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
    path: ./ruleset/Telegram.yaml
    interval: 86400
  OpenAI:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./ruleset/OpenAI.yaml
    interval: 86400
  Twitter:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter.yaml
    path: ./ruleset/Twitter.yaml
    interval: 86400
  GameDownload:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload.yaml
    path: ./Rule/GameDownload.yaml
    interval: 86400
  GameDownloadCN:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.yaml
    path: ./Rule/GameDownloadCN.yaml
    interval: 86400
  Epic:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.yaml
    path: ./Rule/Epic.yaml
    interval: 86400
  Steam:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
    path: ./ruleset/steam.yaml
    interval: 86400
  SteamCN:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.yaml
    path: ./ruleset/steamCN.yaml
    interval: 86400
  GlobalMedia: # 国际媒体
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml
    path: ./ruleset/GlobalMedia.yaml
    interval: 86400
  ProxyLite:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ProxyLite/ProxyLite.yaml
    path: ./ruleset/ProxyLite.yaml
    interval: 86400
  Instagram:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Instagram/Instagram.yaml
    path: ./ruleset/Instagram.yaml
    interval: 86400
  Speedtest:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml
    path: ./ruleset/Speedtest.yaml
    interval: 86400
  Download: 
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Download/Download.yaml
    path: ./ruleset/Download.yaml
    interval: 86400
rules:
  - DOMAIN-SUFFIX,sheerid.com,美国节点
  - RULE-SET,Spotify,Spotify
  - DOMAIN,local.adguard.org,DIRECT
  - DOMAIN-SUFFIX,linux.do,DIRECT
  #P2P 规则
  - RULE-SET,applications,DIRECT
  - DOMAIN-SUFFIX,ai.meta.com,AI
  - DOMAIN-SUFFIX,meta.ai,AI
  - DOMAIN-SUFFIX,copilot.microsoft.com,香港节点
  - DOMAIN-SUFFIX,ciciai.com,狮城节点
  - DOMAIN-SUFFIX,cici.com,狮城节点
  - DOMAIN-SUFFIX,anthropic.com,AI
  - DOMAIN-SUFFIX,perplexity.ai,AI
  - RULE-SET,GameDownloadCN,DIRECT
  - RULE-SET,Epic,DIRECT
  - RULE-SET,SteamCN,DIRECT
  - RULE-SET,Steam,Steam
  - RULE-SET,GameDownload,国外视频
  - RULE-SET,Apple,Apple
  - RULE-SET,Google,Google
  - RULE-SET,Netflix,国外视频
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Telegram,Telegram
  - RULE-SET,OpenAI,AI
  - RULE-SET,GlobalMedia,国外视频
  - RULE-SET,Instagram,Instagram
  - RULE-SET,Speedtest,DIRECT
  - RULE-SET,Twitter,Twitter
  - RULE-SET,ProxyLite,节点选择
  - RULE-SET,Download,DIRECT
  - RULE-SET,ChinaIP,DIRECT
  # 地域规则
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,漏网之鱼
